
os: Visual Studio 2015

matrix:
  fast_finish: true

environment:
  matrix:
    - channel: 1.43.0
      target: i686-pc-windows-msvc
    - channel: 1.43.0
      target: x86_64-pc-windows-msvc

install:
  # Setup Rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --profile=minimal --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  #- cargo test --no-default-features
  - cargo test
  #- cargo test --all-features
